version: '3.5'

services:
  database:
    container_name: postgres-school
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
